apiVersion: v1
kind:  Service
metadata:
      name: loadbalancer
spec:
    selector:
        app:  nginxapp3
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 80
        name: http


# apiVersion: v1
# kind:  Service
# metadata:
#       name: nodeport
# spec:
#     selector:
#         app:  nginxapp2
#     type: NodePort
#     ports:
#       - port: 80
#         targetPort: 80
#         name: http        