# apiVersion: v1
# kind: Pod
# metadata:
#         name: nginxapp
#         #  label:
#         #     app: nginxapp
# spec:
#     containers:
#         - name: nginxcont
#           image: nginx:latest
#           resources:
#               requests:
#                 cpu: "10m"
#                 memory: "12Mi" 
#           ports:
#               - protocol: TCP
#                 containerPort: 80
#                 name: http


apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  # Uncomment this section if you want to use labels
  # labels:
  #   app: nginxapp
spec:
  containers:
    - name: nginxcont
      image: nginx:latest
      resources:
        requests:
          cpu: "10m"
          memory: "12Mi"
      ports:
        - protocol: TCP
          containerPort: 80
          name: http
