# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontendsrv
# spec:
#   type: ClusterIP
#   selector:
#     app: deployappfront 
#   ports:
#     - port: 80
#       targetPort: 80
#       name: http
#       protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: frontendsrv
spec:
  type: ClusterIP
  selector:
    app: deployappfront  # Ensure this matches your traffic light Deployment
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP

