# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontendsrv
# spec:
#   type: ClusterIP
#   selector:
#     app: deployappfront 
#   ports:
#     - port: 80
#       targetPort: 80
#       name: http
#       protocol: TCP

apiVersion: v1
kind: Service
metadata: 
  name: backendsrv
spec:
  type: ClusterIP
  selector:
    app: deployappback  # Ensure this matches your todo Deployment
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
