apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  ReplicaSet-In
  labels:
    app: ReplicaSet-In
  selector:
     matchExpressions:
         - {key: app, operator: In, values: [ReplicaSet-In]}
spec: 
  replicas:
     - name: nginxcont
       image:  nginx:lastest
       resources: 
          requests: 
            cpu: "400m" 
            memory: "100Mi"
       ports:
       - name:  http
         port:  80
         protocol: TCP               
     