apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  ReplicaSet-In
  lables:
    app: ReplicaSet-In
  selector:
     matchExpressions:
         - {key: app, operator: In, values: [ReplicaSet-In]}
spec: 
   containers:
     - name:          
     