# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: nginx-replicaset
#   labels:
#     app: nginx-replicaset
# spec:
#   replicas: 3
#     app: nginx-replicaset
#   template:
#     metadata:
#       labels:
#       app: nginx-replicaset
#     spec:
#       containers:
#         - name: nginxcontainer
#           image: nginx:latest
#           resources:
#             requests:
#               cpu: "500m"
#               memory: "150Mi"
#           ports:
#             - name: https
#               containerPort: 80
#      selector:          
#         app: nginx-replicaset
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-replicaset
spec:
  replicas: 3
  selector:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          resources:
            requests:
              cpu: "500m"
              memory: "150Mi"
          ports:
            - name: https
              containerPort: 80

