apiVersion: apps/v1
kind: ReplicationController
metadata: 
   name: replica-in
   labels: 
      app: replica-in
spec:
    replicas: 4
    selector:
      matchExpressions:
        - {key: app, operator: In, values: [replica-in, replica-in2, replica-in3]}  
    template:  
      metadata:
        labels:
          app: replica-in
      spec:                        # This is where the pod spec starts
        containers:
         - name: nginxcon
           image: nginx:latest
           resources: 
              requests:             # Corrected "requests"
                cpu: "200m"
                memory: "128Mi"         
           ports:
            - protocol: TCP
              containerPort: 80
              name: http

