apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-replicaset
  lables: 
   app: nginx-replicaset
spec: 
replicas: 3
template: 
  metadata: 
    name: nginx-replicaset
    lables:
      app: nginx-replicaset   
      spec:
      containers:
        - name: nginxcontainer
          image: nginx:latest
          resources: 
            requests:
              cpu: "500m"
              memory: "150Mi"
          ports:
          - name:  https
            containerPort:  80
            protocol: TCP  
  selector: 
     matchExpressions: 
       - {key:app, operator: In, values: [nginx-replicaset]}           


