apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: replica-in-02
   labels: 
      app: replica-in-02
spec:
    replicas: 4
    selector:
      matchExpressions:
        - {key: app, operator: Exists}  
    template:  
      metadata:
        labels:
          app: replica-in-01
      spec:                        # This is where the pod spec starts
        containers:
         - name: nginxcon1
           image: nginx:latest
           resources: 
              requests:             # Corrected "requests"
                cpu: "200m"
                memory: "128Mi"         
           ports:
            - protocol: TCP
              containerPort: 80
              name: http
