apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: your-hostname.com  # Replace with your actual hostname or use the external IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontendsrv  # Traffic light service
                port:
                  number: 80
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: backendsrv  # Todo service
                port:
                  number: 8080
