apiVersion: v1  # api version
kind:  PersistentVolume   # type of a k8s object we are usig
metadata: 
  name: efs-pv  # name of volume 
spec: 
  capacity:  # capacity
    storage: 10Gi  # storage allocate to pv 10gb
  volumeMode: Filesystem     # 
  accessModes:
    - ReadWriteOnce  # permissions to access pv
  storageClassName: standard  # storage type 
  persistentVolumeReclaimPolicy: Retain
  csi:      #  Container Storage Interface
    driver: efs.csi.aws.com    
    volumeHandle: fs-04b71a54fef19cd5b # your efs id 

--- 
#pvc
apiVersion: v1  # api version to 
kind: PersistentVolumeClaim  # type of object
metadata: 
  name: efs-claim  #name of pvc
spec: 
 accessModes:
   - ReadWriteOnce  # permissions
 storageClassName: standard  # type of storage
 resources:
    requests:  # storage request to pv or claim
      storage: 5Gi  # claiming storage
