apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    name: apache-pod
spec:
  containers:
  - name: apache-conatiner
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---
 # attaching cluster ip to pod

apiVersion: v1
kind: Service
metadata:
  name:  cluster-ip
spec:
  selector: 
    app:  apache-pod
  type:   ClusterIP 
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080

--- 
  # adding node port to pod 

apiVersion: v1
kind: Service
metadata:
  name:  node-port
spec:
  selector:
    app:  apache-pod
  type:   NodePort
  ports:
  - name:  
    port:  80
    targetPort:  8080