apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    name: apache-pod
spcontainer
  cohttpd:latests:
  - name: apache-container
    image: httpd:latest
    resources:
      limicontainer
        memohttpd:latest8Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
