apiVersion: v1
kind: pod 
metadata: 
    -name: apache-pod
     lables:
         apps: apache-pod
      spec: 
        containers:
          - image:  image
          name:  my-name
          env:
            - name:  ENVVARNAME
              value:  ENVVARVALUE
