apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    name: apache-pod
spec:
  containers:
  - name: apache-conatiner
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---
 # attaching cluster ip to pod

apiVersion: v1
kind: Service
metadata:
  name:  apache-pod
spec:
  selector: apache-pod
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080