apiVersion: v1
kind: service
metadata: 
  name: apache-pod
  labels: 
    apps: apache
spec: 
  containers:
    - image:  image
    name:  my-name
    env:
      - name:  ENVVARNAME
        value:  ENVVARVALUE