apiVersion: v1
kind: pod 
metadata: 
  name: apache-pod
  lables:
    apps: apache-pod
spec: 
  containers: 
      - name: apche-container
        image:  httpd:latest
        ports: 
        ContainerPort: 80
