apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    name: apache-pod
spec:
  containers:
  - name: apache-conatiner
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
